version: '3'
services:
  redis:
    image: redislabs/redis
    container_name: redis    
    ports:
      - 8443:8443
      - 9443:9443
      - 12000:12000
    cap_add:
      - sys_resource
  benchmark:
    image: kyle/redis-benchmark
    container_name: benchmark
    environment:
      - se.connection_string=redis:12000,connectRetry=3,connectTimeout=3000,abortConnect=false
      - ss.connection_string=redis:12000
    command: "/wait-for-it.sh redis:9443 -- /run.sh"